### ISSUE TITLE
Add support for dice annotations & visualization

### ISSUE THREAD

**Issue by csaftoiu** [LogicalInnovation/sloth#1]
## Overview

We have a data acquisition need where we have to annotate [backgammon](https://en.wikipedia.org/wiki/Backgammon) boards with the position of the dice, and what dice face is showing. We have a guy who uses tools to do data acquisition, but right now we have no tool that can do this task easily.

We're going to modify [sloth](https://github.com/cvhciKIT/sloth) to do what we want. This repo is a fork of sloth.

## Task

Right now by default you can annotate points. Example, before:

![image](https://cloud.githubusercontent.com/assets/43113/21583644/eb1ac506-d03e-11e6-9693-d1085e2d58f6.png)

After:

![image](https://cloud.githubusercontent.com/assets/43113/21583646/f544885a-d03e-11e6-992f-f9b63358593a.png)

We need two changes:

* [ ] Set up so we can mark one of 6 different types of points, for "1", "2", "3", "4", "5", "6". Example, with [the config here](http://sloth.readthedocs.io/en/latest/first_steps.html#writing-a-custom-configuration) they added labels for head, left eye, right eye:

    ![image](https://cloud.githubusercontent.com/assets/43113/21583651/271a3d48-d03f-11e6-8a9e-3776762f5f59.png)

* [ ] Change the visualization so it shows the number on the dice face point. Example, it can look something like this instead of the point:

    ![image](https://cloud.githubusercontent.com/assets/43113/21583652/4dd94c4e-d03f-11e6-8aaa-5ebb102047a9.png)

    **However**, you still want to mark a small red 'x' where the center point itself is, since we're marking points, not rects.

    I think [this code](https://github.com/berleon/sloth/commit/090a21c71c44a49e666d67f1b513e262a0fd9eb9) is an example of how to update the visualization.

**Comment by csaftoiu** [comment]
Need to make a subclass of PointItem, called DiceClassItem. This is the same as PointItem except it draws the dice class along with the point. So:

* [x] Make subclass of PointItem
* [x] Override the `paint` method to draw, using Qt5, a small "x" in the center, a box around it, and then the string of the class above or below the rect so that it doesn't obscure the dice face. I believe the class will be accessible in `self._model_item` or perhaps `self._text`.

Then in the LABELS, it will look something like this:

```
LABELS = (
    {"attributes": {"type":  "point", "class": "1"},
     "item":     "sloth.items.DiceClassItem",
     "inserter": "sloth.items.PointItemInserter",
     "text":     "1"
    },
    {"attributes": {"type":  "point", "class": "2"},
     "item":     "sloth.items.DiceClassItem",
     "inserter": "sloth.items.PointItemInserter",
     "text":     "2"
    },
    # etc...
} 
```

**Comment by csaftoiu** [comment]
Moved to https://github.com/LogicalInnovation/bg-data/issues/1.
